# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 3db4e17956cf9d9216abe6977fdd2e5fd137270828749f802befcf580e0681d2ada1797960e885ae38fc10b107c782a5a02e0df81bba112a3e98b32b0b584012

test:
  domain_name: example.com 
  secret_key_base: 05ce51d373085df64a6c6175844087582589f112d7f3670059fef7be83c63655171323c543ab7342cc0f55acef18913be35081149eebc648fcefdbe511ce6917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
